before_script:
  - npm install

pages:
  stage: deploy
  script:
  - npm run build -d public
  artifacts:
    paths:
    - public
  only:
  - Frontend

test:
  stage: test
  script:
  - npm run test
  only:
  - Frontend
